In [77]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [65]:
pd.options.display.float_format = "{:.3f}".format

In [66]:
data = pd.read_csv("~/SGH/data/data_w/bd.csv")

In [67]:
df = data.iloc[:, 0:6]
df.head()

,grupa elementów,element badania,liczba wypożyczonych książek na 100tys.ludności,liczba osób chodzących do kina na 100tys. Ludności,liczba uczestników imprez sportowych na 100tys. Ludności,liczba osób chodzących do teatru i na wystawy na 100tys. Ludności
0,a,1,7711,9600,73253,174
1,a,2,9998,35655,172661,196
2,a,3,5084,118688,151254,89
3,a,4,174,5000,32240,109
4,a,5,3723,5110,57795,2506

In [68]:
df.describe(percentiles=[0.05, 0.95])

,element badania,liczba wypożyczonych książek na 100tys.ludności,liczba osób chodzących do kina na 100tys. Ludności,liczba uczestników imprez sportowych na 100tys. Ludności,liczba osób chodzących do teatru i na wystawy na 100tys. Ludności
count,300.000,300.000,300.000,300.000,300.000
mean,150.500,47004.903,79888.477,101085.500,424.473
std,86.747,180022.780,242536.891,118589.986,832.371
min,1.000,3.000,900.000,65.000,23.000
5%,15.950,230.550,2000.000,15489.800,43.950
50%,150.500,9016.500,14000.000,71809.000,221.000
95%,285.050,175147.950,340572.800,257631.100,1498.700
max,300.000,1731438.000,2570889.000,1008139.000,9603.000

In [74]:
df.groupby(['grupa elementów']).describe(percentiles=[0.05, 0.95]).T

grupa elementów                                                    a  \
element badania                                    count      29.000
                                                   mean       15.000
                                                   std         8.515
                                                   min         1.000
                                                   5%          2.400
                                                   50%        15.000
                                                   95%        27.600
                                                   max        29.000
liczba wypożyczonych książek na 100tys.ludności    count      29.000
                                                   mean    62155.759
                                                   std    183295.245
                                                   min       117.000
                                                   5%        203.600
                                                   50%      4924.000
                                                   95%    409486.000
                                                   max    852817.000
liczba osób chodzących do kina na 100tys. Ludności count      29.000
                                                   mean    82878.172
                                                   std    245832.338
                                                   min      2300.000
                                                   5%       3080.000
                                                   50%     18500.000
                                                   95%    342351.200
                                                   max   1269419.000
liczba uczestników imprez sportowych na 100tys.... count      29.000
                                                   mean   112506.069
                                                   std    121866.939
                                                   min      7700.000
                                                   5%      19600.400
                                                   50%     77521.000
                                                   95%    272237.200
                                                   max    638718.000
liczba osób chodzących do teatru i na wystawy n... count      29.000
                                                   mean      431.310
                                                   std       795.456
                                                   min        23.000
                                                   5%         28.800
                                                   50%       124.000
                                                   95%      2368.400
                                                   max      3180.000

grupa elementów                                                    b  \
element badania                                    count      86.000
                                                   mean       72.500
                                                   std        24.970
                                                   min        30.000
                                                   5%         34.250
                                                   50%        72.500
                                                   95%       110.750
                                                   max       115.000
liczba wypożyczonych książek na 100tys.ludności    count      86.000
                                                   mean    49862.163
                                                   std    206408.972
                                                   min        29.000
                                                   5%        664.000
                                                   50%     10945.500
                                                   95%     52729.000
                                                   max   1731438.000
liczba osób chodzących do kina na 100tys. Ludności count      86.000
                                                   mean    65031.640
                                                   std    200958.638
                                                   min      1000.000
                                                   5%       1625.000
                                                   50%     10200.000
                                                   95%    271271.500
                                                   max   1354014.000
liczba uczestników imprez sportowych na 100tys.... count      86.000
                                                   mean    81450.244
                                                   std    107792.685
                                                   min      3885.000
                                                   5%      15611.250
                                                   50%     60005.000
                                                   95%    184324.000
                                                   max    959257.000
liczba osób chodzących do teatru i na wystawy n... count      86.000
                                                   mean      334.291
                                                   std       380.283
                                                   min        23.000
                                                   5%         49.500
                                                   50%       242.000
                                                   95%       963.750
                                                   max      2193.000

grupa elementów                                                    c  \
element badania                                    count      55.000
                                                   mean      143.000
                                                   std        16.021
                                                   min       116.000
                                                   5%        118.700
                                                   50%       143.000
                                                   95%       167.300
                                                   max       170.000
liczba wypożyczonych książek na 100tys.ludności    count      55.000
                                                   mean    56437.800
                                                   std    210232.326
                                                   min         3.000
                                                   5%        282.100
                                                   50%      9875.000
                                                   95%    190087.800
                                                   max   1503027.000
liczba osób chodzących do kina na 100tys. Ludności count      55.000
                                                   mean    54083.018
                                                   std    231030.005
                                                   min       900.000
                                                   5%       1350.000
                                                   50%     13300.000
                                                   95%    101768.900
                                                   max   1715358.000
liczba uczestników imprez sportowych na 100tys.... count      55.000
                                                   mean   113202.164
                                                   std    137440.812
                                                   min      2970.000
                                                   5%      10741.900
                                                   50%     70461.000
                                                   95%    320930.000
                                                   max    896077.000
liczba osób chodzących do teatru i na wystawy n... count      55.000
                                                   mean      489.636
                                                   std       679.332
                                                   min        43.000
                                                   5%         54.700
                                                   50%       326.000
                                                   95%      1263.700
                                                   max      4654.000

grupa elementów                                                    d  \
element badania                                    count      41.000
                                                   mean      191.000
                                                   std        11.979
                                                   min       171.000
                                                   5%        173.000
                                                   50%       191.000
                                                   95%       209.000
                                                   max       211.000
liczba wypożyczonych książek na 100tys.ludności    count      41.000
                                                   mean    45177.341
                                                   std    128752.407
                                                   min        77.000
                                                   5%        353.000
                                                   50%      9987.000
                                                   95%     95995.000
                                                   max    757216.000
liczba osób chodzących do kina na 100tys. Ludności count      41.000
                                                   mean   117250.707
                                                   std    409791.236
                                                   min      1150.000
                                                   5%       2600.000
                                                   50%     15400.000
                                                   95%    291243.000
                                                   max   2570889.000
liczba uczestników imprez sportowych na 100tys.... count      41.000
                                                   mean   105793.122
                                                   std    153412.556
                                                   min     12635.000
                                                   5%      15182.000
                                                   50%     72380.000
                                                   95%    209409.000
                                                   max   1008139.000
liczba osób chodzących do teatru i na wystawy n... count      41.000
                                                   mean      261.780
                                                   std       249.289
                                                   min        32.000
                                                   5%         52.000
                                                   50%       205.000
                                                   95%       657.000
                                                   max      1349.000

grupa elementów                                                    e  \
element badania                                    count      67.000
                                                   mean      245.000
                                                   std        19.485
                                                   min       212.000
                                                   5%        215.300
                                                   50%       245.000
                                                   95%       274.700
                                                   max       278.000
liczba wypożyczonych książek na 100tys.ludności    count      67.000
                                                   mean    36145.537
                                                   std    161768.383
                                                   min         5.000
                                                   5%        224.700
                                                   50%      8564.000
                                                   95%     82222.400
                                                   max   1313775.000
liczba osób chodzących do kina na 100tys. Ludności count      67.000
                                                   mean    99245.015
                                                   std    191402.253
                                                   min      1401.000
                                                   5%       4060.000
                                                   50%     17500.000
                                                   95%    634821.400
                                                   max    778000.000
liczba uczestników imprez sportowych na 100tys.... count      67.000
                                                   mean   112382.328
                                                   std     97357.259
                                                   min        65.000
                                                   5%      25782.100
                                                   50%     83944.000
                                                   95%    300388.800
                                                   max    564358.000
liczba osób chodzących do teatru i na wystawy n... count      67.000
                                                   mean      424.836
                                                   std       903.451
                                                   min        24.000
                                                   5%         47.000
                                                   50%       195.000
                                                   95%       935.800
                                                   max      6970.000

grupa elementów                                                   f
element badania                                    count     22.000
                                                   mean     289.500
                                                   std        6.494
                                                   min      279.000
                                                   5%       280.050
                                                   50%      289.500
                                                   95%      298.950
                                                   max      300.000
liczba wypożyczonych książek na 100tys.ludności    count     22.000
                                                   mean   28759.409
                                                   std   124098.101
                                                   min       92.000
                                                   5%       358.950
                                                   50%     1050.000
                                                   95%     8914.850
                                                   max   584276.000
liczba osób chodzących do kina na 100tys. Ludności count     22.000
                                                   mean   69958.818
                                                   std   120700.289
                                                   min     1500.000
                                                   5%      2012.850
                                                   50%    14040.000
                                                   95%   334033.850
                                                   max   409292.000
liczba uczestników imprez sportowych na 100tys.... count     22.000
                                                   mean   89318.182
                                                   std    86453.878
                                                   min     4970.000
                                                   5%      9326.750
                                                   50%    63495.000
                                                   95%   210947.450
                                                   max   399679.000
liczba osób chodzących do teatru i na wystawy n... count     22.000
                                                   mean     907.182
                                                   std     2055.509
                                                   min       31.000
                                                   5%        44.250
                                                   50%      186.500
                                                   95%     2557.850
                                                   max     9603.000

In [76]:
df.corr()

,element badania,liczba wypożyczonych książek na 100tys.ludności,liczba osób chodzących do kina na 100tys. Ludności,liczba uczestników imprez sportowych na 100tys. Ludności,liczba osób chodzących do teatru i na wystawy na 100tys. Ludności
element badania,1.000,-0.038,0.044,0.041,0.079
liczba wypożyczonych książek na 100tys.ludności,-0.038,1.000,0.095,0.057,-0.029
liczba osób chodzących do kina na 100tys. Ludności,0.044,0.095,1.000,0.039,-0.003
liczba uczestników imprez sportowych na 100tys. Ludności,0.041,0.057,0.039,1.000,-0.034
liczba osób chodzących do teatru i na wystawy na 100tys. Ludności,0.079,-0.029,-0.003,-0.034,1.000

In [83]:
scaler = preprocessing.StandardScaler().fit(df.iloc[:, 2:6])

In [84]:
df_transformed = scaler.transform(df.iloc[:, 2:6])

In [93]:
df_transformed[0]

array([-0.21863654, -0.29028952, -0.23508734, -0.30141824])